// AppMobileChats/src/Views/Chats.tsx
import React, { useEffect, useState } from "react";
import AsyncStorage from '@react-native-async-storage/async-storage';
import { io } from "socket.io-client";
import { useNavigation } from "@react-navigation/native";
import { StyledView, StyledText, StyledTextInput, StyledTouchableOpacity, StyledImageBackground } from "../shared/styled"; // Asegúrate de que estos componentes estén definidos correctamente en tu proyecto.

const fondo = require("../../assets/fondoChat.png");
const socket = io("http://localhost:3001");
const navigation = useNavigation

const ChatsView = ({ route }) => {

  type Message = {
    id: string;
    user_id: string;
    mensaje: string;
    timestamp: number;
  };
  const [mensajes, setMensajes] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState<string>("");
  const [salaId, setSalaId] = useState<string>("");
  const [myUserId, setMyUserId] = useState<string>("");


    // UseEffect para el user id con localstorege, adaptando despues se metera en redux

  useEffect(() => {
    const  fetchUserId = async () => {
        const userId = await AsyncStorage.getItem("userId")
        setMyUserId(userId || "")
    }

    fetchUserId()
  }, [])

  // UseEffect para el salaid con localstorege, adaptando despues se metera en redux

  useEffect(() => {
    if (myUserId && salaId) {
        socket.emit("JoinRoom", { salaId, userId: myUserId})
        const handleReceiveMessage = (messageData: Message) => {
            setMensajes((prevMensajes) => [...prevMensajes, messageData])
        }
        socket.on("Recieve_message", handleReceiveMessage)

        return () => {
            socket.off("recieve_message", handleReceiveMessage)
            socket.disconnect()
        }
    }
  },[salaId,myUserId])

  const fetchMensajes = async () => {
    try {
        const response = await fetch(`http://10.0.2.2:3001/api/mensajes/${salaId}`);
      if (response.ok) {
        const data = await response.json();
        setMensajes(data);
      } else {
        console.error("Error al cargar los mensajes");
      }
    } catch (error) {
      console.error("Error al conectar con el servidor:", error);
    }
  };

  const sendMessage = async () => {
    if (!newMessage) return;

    try {
      const response = await fetch("http://10.0.2.2:3001/api/mensajes", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          salaId,
          userId: myUserId,
          mensaje: newMessage,
        }),
      });

      if (response.ok) {
        setNewMessage(""); // Clear the input field after sending
      } else {
        console.error("Error al enviar el mensaje");
      }
    } catch (error) {
      console.error("Error al conectar con el servidor:", error);
    }
  };

  const renderItem = ({ item }: {item: Message}) => (
    <StyledView
      className={`flex flex-col mb-4 ${
        item.user_id.toLowerCase() === myUserId.toLowerCase() ? "items-end" : "items-start"
      }`}
    >
      <StyledText className="text-white font-black text-lg">{item.user_id}:</StyledText>
      <StyledText className="text-white max-w-[450px] rounded-xl px-2 break-words bg-[#212121]">
        {item.mensaje}
      </StyledText>
      <StyledText className="text-white text-xs">
        {new Date(item.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
      </StyledText>
    </StyledView>
  );

  return (
    <StyledView className="w-full h-full flex-col">
      <StyledView className="bg-[#212121] w-full h-[90px] p-3 justify-center items-center">
        <StyledText className="text-white text-xl font-bold">{salaId}</StyledText>
      </StyledView>

      <StyledImageBackground
        className="flex-1 bg-[#281437] bg-cover bg-center bg-no-repeat px-10"
        source={fondo} style={{flex: 1}}
      >

        <StyledView className="w-full h-full mb-10 pb-4">
          <StyledView className="h-3/4">
            <StyledView>
              {mensajes.map((message) => (
                <StyledView key={message.id} className="flex-col mb-4">
                  <StyledText className="text-white font-black text-lg">{message.user_id}:</StyledText>
                  <StyledText className="text-white max-w-[450px] rounded-xl px-2 break-words bg-[#212121]">
                    {message.mensaje}
                  </StyledText>
                  <StyledText className="text-white text-xs">
                    {new Date(message.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                  </StyledText>
                </StyledView>
              ))}
            </StyledView>
          </StyledView>

          <StyledView className=" z-10 w-full h-1/4 mt-4">
            <StyledTextInput
              value={newMessage}
              onChangeText={setNewMessage}
              onSubmitEditing={sendMessage}
              placeholder="Mensaje"
              className="bg-[#212121] text-white w-full h-[50px] rounded-2xl outline-none p-4"
            />
            <StyledTouchableOpacity onPress={sendMessage} className="rounded-full bg-[#7963DD] w-[45px] h-[45px] justify-center items-center">
              <StyledText className="text-white">SEND</StyledText>
            </StyledTouchableOpacity>
          </StyledView>
        </StyledView>
      </StyledImageBackground>
    </StyledView>
  );
};

export default ChatsView;

// Frontend/src/views/Chats.vue
<template>
    <section class="flex w-full h-full gap-[1px]">
      <section class="w-[580px] h-screen bg-[#212121] text-white">
        <div class="text-center p-2"> User Online </div>
        <div class="flex flex-col gap-1 px-5"> 
    
        </div>

      </section>
      <section class="w-full h-screen flex flex-col">
        <div class="bg-[#212121] text-white text-center w-full h-[90px] p-3"> RoomId:  {{ salaId }}</div> 
        <div :style="{ backgroundImage: `url(${fondo})` }" class="fondotelegram bg-[#281437] bg-cover bg-center bg-no-repeat w-full h-full flex opacity-100 px-[210px]">  
          <div class="chat flex flex-col w-full gap-1 pb-4">
                <div class="mensajes h-full">
                  <div
                    v-for="message in mensajes"
                    :key="message.id"
                    :class="{'my-message': message.user_id.toLowerCase() === MyuserId.toLowerCase(), 
                    'guest-message': message.user_id.toLowerCase() !== MyuserId.toLowerCase()}"
                    :style="{
                      textAlign: message.user_id === MyuserId ? 'right' : 'left'
                    }"
                    >
                    <p class="flex flex-col">
                      <span class="text-white font-black text-lg">{{ message.user_id }}:</span>
                      <span class=" text-white max-w-[450px] rounded-xl px-2 break-words">{{ message.mensaje }}</span>
                    </p>
                    <span class="text-white text-xs">{{ new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }}</span>
                  </div>
                </div>
                <div class="flex gap-1">
                    <input v-model="newMessage" @keyup.enter="sendMenssage" type="text" placeholder="Mensaje" class="bg-[#212121] text-white w-full h-[50px] rounded-2xl outline-none p-4">
                    <button @click="sendMenssage" class="rounded-full bg-[#7963DD] w-[45px] h-[45px] flex justify-center items-center"> <send class="text-white" /> </button>
                </div>
            </div>
        </div>
      </section>
    </section>
  </template>
  
  <script setup>
  import fondo from '../assets/descarga.png'
  import send from '../assets/send.vue'
  import { onMounted, onUnmounted, ref, nextTick, watch } from 'vue';
  import { io } from 'socket.io-client'
  import { useRoute } from 'vue-router';

  const mensajes = ref([])
  const MyuserId = ref(localStorage.getItem('userId') || '')
  const newMessage = ref('')
  const salaId = ref(localStorage.getItem('salaId') || '')
  const socket = io('http://localhost:3001')
  // const users = ref([]) 
  const route = useRoute()
  // const usernameMsg = ref (localStorage.getItem('usuario') || '')

  onMounted(() => {
  const salaId = route.params.salaId
  localStorage.setItem('salaId', salaId)
});

// console.log(MyuserId.value)
// console.log(salaId.value)


    const fetchMensajes = async () => {
      try {
      const response = await fetch (`http://localhost:3001/api/mensajes/${salaId.value}`)
      if(response.ok) {
        mensajes.value = await response.json()
      } else {
        console.error('Error al cargar los mensajes')
        }
      } catch (error) {
        console.error('Error al conectar con el servidor:', error)
      }
    };

//   const fetchUsuarios = async () => {         AUN ESTA EN BETA LOS USUARIOS ONLINE
//     try {
//       const response = await fetch(`http://localhost:3001/api/usuarios/${salaId.value}`)
//       if (response.ok) {
//         users.value = await response.json()
//       } else {
//         console.error('Error al cargar los usuarios')
//       }
//     } catch (error) {
//       console.error('Error al conectar con el servidor:', error)
//     }
// };

    const sendMenssage = async () => {
      if (!newMessage.value) return

      try {
        const response = await fetch ('http://localhost:3001/api/mensajes', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            salaId: salaId.value,
            userId: MyuserId.value,
            mensaje: newMessage.value,
            // usuario: usernameMsg.value
          })
        });
        if(response.ok) {
          // const   newMsg = await response.json()
          // mensajes.value.unshift(newMsg)
          newMessage.value = ''
        } else {
          console.error('Error al enviar el mensaje')
        }
      } catch (error) {
        console.error('Error al conectar con el servicor:', error)
      }
    };

    onMounted(() => {
  fetchMensajes()
  // fetchUsuarios()

  socket.emit('join_room', salaId.value)
  socket.on('receive_message', (messageData) => {
    mensajes.value.push(messageData)
  })
  // socket.on('update_users', (userList) => {
  //   users.value = userList
  // })
})

onUnmounted(() => {
  socket.disconnect()
})

console.log(MyuserId.value)
  </script>
  

<style scoped>
  input::placeholder {
    color: rgb(150, 150, 150);
    opacity: 1;
  }

  .mensajes {
  display: flex;
  flex-direction: column;
  overflow-y: auto; 
  height: calc(100vh - 120px);
  padding: 10px;
}

.my-message {
  display: flex;
  flex-direction: column;
  align-items: end;
} 

.guest-message {
  display: flex;
  flex-direction: column;
  align-items: start;
}


</style>
